#
## .bashrc for mac
#

PS1='\[\033[00;32m\]$(date +%H:%M)\[\033[00m\] \[\033[00;36m\]$(echo $(basename "${PWD%/*}" 2>/dev/null)/"$(basename "$PWD")" | sed "s;//;/;"  )\[\033[00m\] \$ ' 

[ -f ~/.aliasrc ] && . ~/.aliasrc
[ -f ~/.exportrc ] &&. ~/.exportrc

#[ -f ~/.bash_profile ] && . ~/.bash_profile


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
